---
title: "Research"
toc: true
---

## Working Papers

##### Caraher, Raymond. "Do Abortion Bans Affect Reproductive and Infant Health? Evidence from Texas’s 2021 Ban and its Impact on Health Disparities." *Political Economy Research Institute* (PERI) Working Paper 606 (2024).

::: {.callout-note appearance="simple" collapse="true"}
# Abstract

The overturning of Roe v. Wade led to a wave of abortion bans in state legislatures across the United States. This emergence of a restrictive reproductive health policy environment has the potential to affect a wide range of reproductive health outcomes. This paper uses Texas’s 2021 6-week ban on abortion as a case study to examine the causal effect of an abortion ban on reproductive health outcomes, specifically abortion rates, fertility rates, and infant health outcomes. It examines how these effects may be heterogeneous by group, especially focusing on how the effects of abortion bans on reproductive health may be concentrated in those who are already facing disparities in reproductive health outcomes such as Black women. Using a difference-in-differences strategy, the analysis finds that the ban decreased abortion rates by over 40 percent, and increased fertility rates by about 4 percent, with the largest increases for Black non-Hispanic women and for counties far from a state with less restrictive abortion laws. This paper then constructs a measure of unmet reproductive health needs after an abortion ban, and finds that the unmet needs after the Texas 6-week ban are largest in counties with higher proportions of Black non-Hispanic residents, as well as counties which are furthest away from states which did not ban abortion after the Dobbs decision. The analysis then examines the effect of the ban on infant health outcomes, specifically focusing on heterogeneity in the effect of the ban on birth weight and infant mortality. This paper finds that the ban led to increases in the probability of an infant being born with very low birth weight of about 7 percent, with Black non-Hispanic infants experiencing the largest increases in the likelihood of very low birth weight. Additionally, the analysis finds significant increases in the infant mortality rate of about 6 percent after the abortion ban, again with Black non-Hispanic infants experiencing the largest increases in mortality. Further, the ban increased infant mortality rates more in counties which are further away from states which did not ban abortion after the Dobbs decision. The results suggest that the effects of abortion bans tend to be especially concentrated in marginalized populations, as well as those who are least able to shift their fertility options away from in-state abortions after a ban. The analysis shows that the trend towards an increasing number abortion bans will further exacerbate disparities in reproductive health outcomes

:::

::: {.callout-tip appearance="minimal"}

{{< iconify iconoir:page-edit size=1.2em title='Preprint' >}} [Preprint](https://ssrn.com/abstract=4911886) 

:::


##### Caraher, Raymond. "Reproductive Injustice? A County-Level Analysis of the Impact of Abortion Restrictions on Abortion Rates." *Political Economy Research Institute* (PERI) Working Paper 573 (2023).

::: {.callout-note appearance="simple" collapse="true"}
# Abstract

Since Planned Parenthood v. Casey in 1992, state governments in the United States have been permitted to restrict abortion access up to the point where such restrictions do not place an ‘’undue burden” on those seeking abortion care. Since this ruling, abortion restrictions of various types and intensities have proliferated across the South and Midwest, especially since the 2010s. This paper uses a novel dataset of county-level abortion rates covering 20 years, as well as a database covering four types of restrictions which represent both “demand-side” restrictions (i.e., those which target abortion seekers) and “supply-side” restrictions (i.e., those which target abortion providers), to analyze the effect of abortion restrictions on abortion rates. Using a difference-in-differences design, the analysis finds that while both classes of abortion restrictions reduce the abortion rate, restrictions that target pregnant people seeking an abortion have a substantially larger effect on abortion rates. Leveraging the spatial heterogeneity of the county-level dataset, the analysis further finds that abortion restrictions have a substantially larger negative effect on abortion rates for counties which have a larger share of Black or Hispanic residents. When comparing high and low income counties, the results suggest that poorer counties experience a higher negative effect of abortion restrictions. Further, the study finds significant variation in the effect of different abortion restrictions by state. While demand-side laws consistently cause abortion rates to decrease, the results for supply- side laws are more heterogenous. Overall, the results suggest that repealing Roe v. Wade will have a significant and unequal effect on abortion rates, with marginalized communities experiencing a greater impact.

:::

::: {.callout-tip appearance="minimal"}

{{< iconify iconoir:page-edit size=1.2em title='Preprint' >}} [Preprint](http://dx.doi.org/10.2139/ssrn.4381662) 

:::

##### Pickbourn, Lynda, Raymond Caraher, and Léonce Ndikumana. "Does Project-Level Aid for Water and Sanitation Improve Child Health Outcomes? Evidence from Household Panel Data in Uganda." *WIDER* Working Paper 2022/141 (2022).

::: {.callout-note appearance="simple" collapse="true"}
# Abstract

Empirical studies on the effectiveness of aid to the water, sanitation, and hygiene sector (WASH aid) have focused primarily on access to these services as the benchmark for evaluating the effectiveness of aid in this sector. 
Given the importance of WASH services for public health outcomes, 
the effectiveness of WASH aid should also be evaluated in terms of its impact on health outcomes. 
This is especially important in low- and middle-income countries where achieving sustained improvements in child health outcomes remains a challenge. 
This paper uses geocoded sub-national data on the location of WASH aid projects in Uganda in conjunction with six waves of nationally representative household-level panel survey data to examine the impact of aid-funded WASH projects on the probability of stunting among Ugandan children and infants. 
Analysing aid effectiveness at the sub-national level avoids the problems of cross-country heterogeneity in aid effectiveness that plagues other studies. 
Results of the difference-in-differences regression analysis suggest that proximity to an aid-funded WASH project reduces the probability of stunting by 14– 21 per cent. 
The results suggest that scaling up aid to the WASH sector can help improve child health outcomes in the country.

:::

::: {.callout-tip appearance="minimal"}

{{< iconify iconoir:page-edit size=1.2em title='Preprint' >}} [Preprint](https://doi.org/10.35188/UNU-WIDER/2022/274-4) 

:::

## Peer-Reviewed Publications

##### Caraher, Raymond and Michael Ash. "Genetic Diversity and Economic Development: Assessing the Key Findings in Ashraf and Galor (2013).” Current Anthropology (*forthcoming*).

::: {.callout-note appearance="simple" collapse="true"}
# Abstract

We replicate Ashraf and Galor (2013) and find that its conclusions concerning the association between human genetic diversity and economic development depend substantially on data selection. 
We incorporate additional genetic data from the Americas and find that the "hump-shaped" relationship between genetic diversity and economic development is not statistically robust. 
We also find that the results in Ashraf and Galor (2013) are sensitive to the selection of covariates, 
in particular the definition of continent fixed-effects. 
Additionally, we update the population data from the Americas using a more current source and find the magnitude of the relationship between economic development and genetic diversity drops substantially. 
Further, we find that the results in Ashraf and Galor (2013) analyzing contemporary GDP are dependent on the "ancestry-adjusted" component of genetic diversity. 
Lastly, we correct a coding error in Ashraf and Galor (2013) and find that the analysis of the mechanisms of trust and innovation are not robust to this correction.

:::

::: {.callout-tip appearance="minimal"}

{{< iconify iconoir:page-edit size=1.2em title='Preprint' >}} [Preprint](https://doi.org/https://doi.org/10.7275/11867619)

:::

##### Pickbourn, Lynda, Raymond Caraher, and Léonce Ndikumana. "Does Project-Level Foreign Aid Increase Access to Improved Water Sources? Evidence from Household Panel Data in Uganda." World Development 158 (2022): 105994. <https://doi.org/10.1016/j.worlddev.2022.105994>.

::: {.callout-note appearance="simple" collapse="true"}
# Abstract

Empirical evidence from cross-country studies on the effectiveness of aid to the water, sanitation and hygiene sector (WASH aid) points to significant heterogeneity across countries and 
highlights the need for further research at the sub-national level to assess and quantify the effectiveness of WASH aid within countries. 
This paper combines geocoded sub-national data on the location of WASH aid projects in Uganda with nationally representative household-level panel survey data to examine whether proximity to aid-funded WASH projects improves household access to water. 
Access to water is evaluated along three dimensions: access to an improved water source, travel time to an improved water source and waiting time at an improved water source. 
The results of a difference-in-difference regression analysis suggest that while aid-funded WASH projects increase household access to improved sources of water, 
households may also see the time burden of water collection increase, 
as they may need to travel longer distances and also experience longer wait times due to congestion at water service points. 
This is an indication that the supply of improved water sources financed by WASH aid in Uganda remains insufficient relative to demand as measured by the population density.

:::

::: {.callout-tip appearance="minimal"}

{{< iconify iconoir:journal size=1.2em title='Preprint' >}} [Final Version](https://doi.org/10.1016/j.worlddev.2022.105994) \

{{< iconify iconoir:page-edit size=1.2em title='Preprint' >}} [Preprint](https://doi.org/https://doi.org/10.7275/27118338) \

{{< iconify iconoir:database size=1.2em title='Preprint' >}} [Data and Code](https://doi.org/10.7910/DVN/I7ASBJ) \

:::