---
title: "Teaching"
title-block-banner: true
---

## Instructor

### Econometrics
##### EC325 | Colby College


::: {.callout-note  appearance="default" collapse="true"}
# About the Course

This course explores the measurement and evaluation of economic models, bridging economic theory with empirical analysis. The emphasis throughout is on building intuitive understanding and applying econometric techniques to real-world problems encountered in public policy. With a focus on causality as our guiding theme, we begin by establishing a framework for causal inference based on the gold standard of randomized trials—a foundation that will inform our approach throughout the course. We then introduce the workhorse of econometric analysis: the linear regression model. You’ll learn about its statistical properties and limitations, and how to interpret and communicate econometric results effectively. Building on this foundation, we explore how to apply these tools to real-life scenarios, covering categorical variables, non-linear relationships, binary outcomes, and other specialized models. The course concludes with advanced econometric techniques for analyzing two particularly powerful types of data: panel data and time series data. Econometrics demands a diverse skill set encompassing mathematics, statistics, economic theory, programming, and written and verbal communication. Perhaps most importantly, it requires developing strong intuition. This course will equip you with the analytical tools and empirical methods essential for modern economic research and policy analysis.

:::

::: {.callout-tip appearance="minimal"}
# Course Materials

{{< iconify iconoir:map size=1.2em title='Syllabus' >}} [Sample Syllabus](files/ec325_syllabus.html)

{{< iconify iconoir:book size=1.2em title='Lecture Notes' >}} [Lecture Notes](https://www.raymondcaraher.com/ec325/)

:::

### The Political Economy of Public Health
##### EC316 | Colby College


::: {.callout-note  appearance="default" collapse="true"}
# About the Course

This course examines the intersections between economics, social institutions, and population health outcomes. Students will explore how social, economic, and political structures influence—and are influenced by—patterns of health and illness. The course adopts a multidisciplinary approach, incorporating statistical methods, econometrics, formal economic modeling, historical analysis, qualitative research, and political economy frameworks.

The course is organized into three main modules.
The first module, Public Health in Historical Context, explores the foundational links between political-economic change and population health. We will examine major historical transitions, from the Black Death to the Industrial Revolution, and trace the origins of the modern healthcare system, including the rise of the medical profession and the impact of early large-scale public health investments.

The second module, Models of Health and Healthcare, shifts to economic theory. We will apply microeconomic models to understand the unique features of healthcare markets, including the demand for health, the role of risk and insurance, and problems of adverse selection. We will also compare the structure of the U.S. healthcare system with international models of provisioning care.

The final module, The Social and Political Determinants of Health, applies these historical and theoretical frameworks to critical contemporary issues. We will investigate deep-rooted health disparities along racial, class, and gender lines; and analyze the influence of corporate power on public health. We conclude by examining the health consequences of major economic crises, such as de-industrialization, austerity, and the rise in "deaths of despair."

:::

::: {.callout-tip appearance="minimal"}
# Course Materials

{{< iconify iconoir:map size=1.2em title='Syllabus' >}} [Sample Syllabus](files/ec316_syllabus.html)


:::



### Economics in the Age of Big Data
##### ECON 337 | University of Massachusetts Amherst


::: {.callout-note  appearance="default" collapse="true"}
# About the Course

We are living in the age of Big Data.
In these “data-driven" times, the potential for addressing critical socio-economic issues related to
education, health, poverty, climate change, and more is immense. However, it also brings to light serious ethical dilemmas and challenges. Throughout history, data has been a tool for social progress, but also as a means to justify social inequalities and the policies which exacerbate them. The era of Big Data is no different.
This course focuses on the practical applications of Big Data for social scientists and policymakers. We will learn the basic theory and skills for basic analysis of Big Data, and apply them to several of the pressing social problems facing the world today. However, we will also develop a critical perspective on the role of data in society and policy by focusing on historical and recent case studies of how data was used to justify social and economic inequalities. The course is divided into three modules. The first module is designed to introduce you to some of the historical misuses of data along with the political and ethical complexities associated with the rise of Big Data, Machine Learning, and AI. In the second module, you will gain practical knowledge and hands-on experience with data manipulation and analysis using the R programming language. In the last module, we will explore how Big Data has revolutionized the social sciences. We will delve into recent advancements that have expanded the possibilities of empirical analysis, enabling us to extract valuable insights from vast datasets.

:::

::: {.callout-tip appearance="minimal"}
# Course Materials

{{< iconify devicon:notion size=1.2em title='Notion' >}} [Sample Course Website](https://rcaraher.notion.site/Econ-337-Economics-in-the-Age-of-Big-Data-c3f04a1211d646329a881ffca8b675d4?pvs=4)


{{< iconify iconoir:map size=1.2em title='Syllabus' >}} [Sample Syllabus](https://drive.google.com/file/d/1f3M_XSOoNqP5dEBItPGRL1SR7gmdPmEU/view?usp=share_link)


:::

### Introduction to Microeconomics
##### ECON 103 | University of Massachusetts Amherst


::: {.callout-note appearance="default" collapse="true"}
# About the Course

Economics 103 is a general education course in the Social World. It is designed to help you to arrive at a better understanding of yourself and other people and involves writing and analytical and critical thinking as well as the development of technical skills. Econ 103 introduces students to the fundamental questions in social theory: the nature of society and the relationship between individuals and the community in the construction of an economic system. While a course in economic and social theory, theories are taught through examples that illustrate their use in practice and the implications of these different approaches. We look at the meaning and value of economic growth, the importance of market externalities and alternative ways to regulate them, the relationship between economic inequality and economic growth, and the meaning and role of social insurance. An underlying theme of Econ 103 is how our choice of economic theory informs our choice of economic policy and our collective action.

:::

::: {.callout-tip appearance="minimal"}
# Course Materials

{{< iconify iconoir:map size=1.2em title='Syllabus' >}} [Sample Syllabus](https://drive.google.com/file/d/1KvMJJts9izS_X3CuxputQs13jSL-it4r/view?usp=share_link)

:::


## Teaching Assistant

#### Empirical Methods in Labor Economics
##### ECON 755 (PhD-level) | University of Massachusetts Amherst
Spring 2025

#### Money and Banking
##### ECON 311 | University of Massachusetts Amherst
Spring 2023

#### Intermediate Microeconomics
##### ECON 203 | University of Massachusetts Amherst
Fall 2024

#### Introduction to Microeconomics
##### ECON 103 | University of Massachusetts Amherst
Spring 2024, Spring 2022, Fall 2019

#### Introduction to Macroeconomics
##### ECON 104 | University of Massachusetts Amherst
Fall 2018

